web/src/python/nimbusweb/portal/nimbus/urls.py
from django.conf.urls.defaults import *
from django.contrib.auth.views import login, logout, password_change, password_change_done

urlpatterns = patterns('nimbusweb.portal.nimbus.views',
    (r'^$', 'index'),
    (r'^profile/$', 'profile'),
    (r'^profile/usercert.pem$', 'download_cert'),
    (r'^profile/userkey.pem$', 'download_key'),
    (r'^profile/cloud.properties$', 'download_propsfile'),
    (r'^admin/$', 'admin'),
    (r'^accounts/$', 'accounts'),
    (r'^register/token/(?P<token>.*)/$', 'register'),
    (r'^accounts/password/$', password_change, {'template_name': 'nimbus/password.html'}),
    (r'^accounts/password/done/$', password_change_done, {'template_name': 'nimbus/password_done.html'}),
    (r'^accounts/login/$',  login, {'template_name': 'nimbus/login.html'}),
    (r'^accounts/logout/$', logout, {'template_name': 'nimbus/logout.html'}),
)

web/src/python/nimbusweb/portal/urls.py
from django.conf.urls.defaults import *
from django.contrib import admin
from django.views.static import serve

import settings
import welcome

admin.autodiscover()

urlpatterns = patterns('',
    (r'^$', "nimbusweb.portal.welcome.views.index"),
    (r'^admin/', include(admin.site.urls)),
    (r'^nimbus/', include("nimbusweb.portal.nimbus.urls")),
)

_media_url = settings.MEDIA_URL
if _media_url.startswith('/'):
    _media_url = _media_url[1:]
urlpatterns += patterns('',
                        (r'^%s(?P<path>.*)$' % _media_url,
                        serve,
                        {'document_root': settings.MEDIA_ROOT}))
del(_media_url, serve)

web/src/python/nimbusweb/portal/nimbus/models.py
import sys
from django.db import models
from django.contrib.auth.models import User, UserManager

class TokenFailure(models.Model):
    ip = models.IPAddressField(primary_key=True)
    count = models.IntegerField()

# ------------- User account, extra information --------------

class UserProfile(models.Model):
    """Extension to properties in django's user model, we hang things off the user record."""
    
    # Required field
    user = models.ForeignKey(User, unique=True, related_name="%(class)s_related")

    # The rest is up to us:
    initial_login_key = models.CharField(max_length=100)
    login_key_expires = models.DateTimeField(auto_now=False, null=True)
    login_key_used = models.DateTimeField(auto_now=False, null=True)
    registration_complete = models.BooleanField()
    registration_ip = models.IPAddressField(null=True)
    cert = models.TextField(null=True)
    certkey = models.TextField(null=True)
    certkey_ip = models.IPAddressField(null=True)
    certkey_time = models.DateTimeField(auto_now=False, null=True)
    query_canonical = models.TextField(null=True)
    query_id = models.TextField(null=True)
    query_secret = models.TextField(null=True)
    cloudprop_file = models.TextField(null=True)
    nimbus_userid = models.TextField(null=True)
    

def user_post_save(sender, instance, **kwargs):
    profile, new = UserProfile.objects.get_or_create(user=instance)
models.signals.post_save.connect(user_post_save, User)

def user_post_delete(sender, instance, **kwargs):
    profile = UserProfile.objects.get_or_create(user=instance)
    profile.delete()
models.signals.post_delete.connect(user_post_delete, User)

web/src/python/nimbusweb/portal/nimbus/forms.py
from django import forms

class NewUserForm(forms.Form):
    username = forms.CharField()
    firstname = forms.CharField()
    lastname = forms.CharField()
    email = forms.EmailField()
    cert = forms.FileField(required=False)
    key = forms.FileField(required=False)
    query_canonical = forms.CharField(required=False)
    query_id = forms.CharField(required=False)
    query_secret = forms.CharField(required=False)
    
    class KEYS:
        """don't screw up typing strings in multiple places"""
        username = "username"
        firstname = "firstname"
        lastname = "lastname"
        email = "email"
        cert = "cert"
        key = "key"
        query_canonical = "query_canonical"
        query_id = "query_id"
        query_secret = "query_secret"

    def clean_common(self, name, allow_empty=False):
        """Adds strip() to string validation.  
        The django cleaning functions accept extraneous spaces, even strings that are just spaces.  (email validation does not)
        """
        x = self.cleaned_data[name]
        x = x.strip()
        if (not x) and (not allow_empty):
            raise forms.ValidationError("Must contain actual characters")
        return x

    def clean_username(self):
        return self.clean_common(self.KEYS.username)

    def clean_firstname(self):
        return self.clean_common(self.KEYS.firstname)
        
    def clean_lastname(self):
        return self.clean_common(self.KEYS.lastname)

    def clean_query_canonical(self):
        return self.clean_common(self.KEYS.query_canonical, allow_empty=True)

    def clean_query_id(self):
        return self.clean_common(self.KEYS.query_id, allow_empty=True)

    def clean_query_secret(self):
        return self.clean_common(self.KEYS.query_secret, allow_empty=True)

web/src/python/nimbusweb/portal/nimbus/views.py
from django.shortcuts import render_to_response
import nimbusweb.portal.settings as settings
from django.contrib.auth.decorators import login_required, user_passes_test
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from datetime import datetime
import adminops
import forms

# -----------------------------------------------------------------------------
# User views
# -----------------------------------------------------------------------------

def index(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect(reverse('nimbusweb.portal.nimbus.views.profile'))
    message = "Welcome!"
    accountprompt = settings.NIMBUS_ACCOUNT_PROMPT
    return render_to_response('nimbus/index.html', 
                              {'message': message, 
                               'accountprompt':accountprompt})

def accounts(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect(reverse('nimbusweb.portal.nimbus.views.profile'))
    else:
        return HttpResponseRedirect(reverse('nimbusweb.portal.nimbus.views.index'))
        
        
def register(request, token):
    if request.user.is_authenticated():
        # This does not make sense if they are already logged in
        return HttpResponseRedirect(reverse('nimbusweb.portal.nimbus.views.profile'))
        
    if not token or not token.strip():
        return HttpResponse("Token missing.")
        
    # Outright deny an IP address that has tried and failed with 10 tokens
    ip = request.META['REMOTE_ADDR']
    if not adminops.ok_token_attempt(ip, 10):
        resp = HttpResponse("Your IP has been banned.")
        resp.status_code = 403
        return resp
        
    resp = adminops.check_token(ip, token)
    if resp:
        return resp
        
    user = adminops.token_to_user(token)
    if not user:
        resp = HttpResponse("Cannot locate account.")
        resp.status_code = 403
        return resp
    
    new_password1 = None
    new_password2 = None
    if "new_password1" in request.POST:
        new_password1 = request.POST['new_password1']
    if "new_password2" in request.POST:
        new_password2 = request.POST['new_password2']
    
    if new_password1 and new_password2:
        new_password1 = new_password1.strip()
        new_password2 = new_password2.strip()
        if new_password1 != new_password2:
            flash_msg = "Passwords don't match."
            return render_to_response('nimbus/register.html', 
                              {'flash_msg': flash_msg,
                               'user': user})
        else:
            if len(new_password2) < 12:
                flash_msg = "Password is not 12 characters or more."
                return render_to_response('nimbus/register.html', 
                                          {'flash_msg': flash_msg,
                                           'user': user})
            
            user.set_password(new_password2)
            user.save()
            
            up = user.get_profile()
            up.registration_complete = True
            up.registration_ip = ip
            up.save()
            
            return HttpResponseRedirect(reverse('nimbusweb.portal.nimbus.views.index'))
        
    return render_to_response('nimbus/register.html', 
                              {'user': user})
    

@login_required
def profile(request):
    user = request.user
    message = "Hello"
    if user.first_name:
        message += ", %s" % user.first_name
    message += "!"
    
    cert_present = False
    key_present = False
    query_present = False
    props_present = False

    up = user.get_profile()
    if up.cert:
        cert_present = True
    if up.certkey:
        key_present = True
    if up.query_id and up.query_secret:
        query_present = True
    if up.cloudprop_file:
        props_present = True
    
    templateparams = {'message': message, 
                      'user': user,
                      'cert_present': cert_present,
                      'key_present': key_present,
                      'access_present': query_present,
                      'props_present': props_present,
                      'canonical_id': up.query_canonical,
                      'access_key': up.query_id,
                      'access_secret': up.query_secret
                     }
    return render_to_response('nimbus/profile.html', templateparams)

@login_required
def download_cert(request):
    up = request.user.get_profile()
    if not up.cert:
        resp = HttpResponse("Your have no certificate on file.")
        resp.status_code = 404
        return resp
    resp = HttpResponse(up.cert, mimetype="application/octet-stream")
    return resp

@login_required
def download_propsfile(request):
    up = request.user.get_profile()
    if not up.cert:
        resp = HttpResponse("Your have no cloud.properties on file.")
        resp.status_code = 404
        return resp
    resp = HttpResponse(up.cloudprop_file, mimetype="application/octet-stream")
    return resp
    
@login_required
def download_key(request):
    up = request.user.get_profile()
    if not up.certkey:
        # The theory here is that they would not know about this page unless
        # they tried once, failed to download, and were trying again.
        # People trying the URL without a referrer might not have ever had
        # a key, oh well.
        resp = HttpResponse("404<br><br><p>You have no key on file.</p><p>It can only be retrieved once.</p><p>If you did not obtain the key, contact your administrator immediately.</p>")
        resp.status_code = 404
        return resp
    
    ip = request.META['REMOTE_ADDR']
    
    resp = HttpResponse(up.certkey, mimetype="application/octet-stream")
    up.certkey = None
    up.certkey_ip = ip
    up.certkey_time = datetime.now()
    up.save()
    return resp

# -----------------------------------------------------------------------------
# Superuser views
# -----------------------------------------------------------------------------

@login_required
def admin(request):
    if not request.user.is_superuser:
        return HttpResponseRedirect(reverse('nimbusweb.portal.nimbus.views.profile'))
    
    flash_msg = None
    ok_flash_msg = None
    newuserform = None
    
    # check if this was a POST to change anything
    if 'op' in request.POST:
        (flash_msg, ok_flash_msg, newuserform) = adminops.admin_post_op(request)
    
    if not newuserform:
        newuserform = forms.NewUserForm()
        
    # bypasses 'pending user' inclusion for superusers (superusers are created
    # out of band)
    up = request.user.get_profile()
    if not up.login_key_used:
        up.login_key_used = datetime.now()
        up.save()
    
    pendingusers = adminops.pendingusers()
    
    recentusers = adminops.recentusers()
    
    templateparams = {'pendingusers': pendingusers,
                      'recentusers': recentusers,
                      'newuserform': newuserform,
                      'flash_msg': flash_msg,
                      'ok_flash_msg': ok_flash_msg,
                      }
    
    return render_to_response('nimbus/admin.html', templateparams)

web/src/python/nimbusweb/portal/templates/nimbus/admin.html
{% extends "base.html" %}

{% block title %}User Administration{% endblock title %}

{% block content %}

    <div class="section">
    
        <h1>Create a new user</h1>
        <p>
            You need to provide details here and then deliver the generated URL in an email from yourself to the intended user.
        </p>
        <p>
            The user will use the URL to initially log in, choose a password, and retrieve the new credential.
        </p>
        
        {% if newuserform.errors %}
            <p class="formerror">
                Please correct the error{{ newuserform.errors|pluralize }} below.
            </p>
        {% endif %}
        
        <div class="newuser">
            <form action="" method="post" enctype="multipart/form-data">
                <div class="frow">
                    <label for="id_username" class="flabel">Username:</label>
                    <span class="finput">
                    {{ newuserform.username }}
                    </span>
                    {{ newuserform.username.errors }}
                </div>
                
                <div class="frow">
                    <label for="id_firstname" class="flabel">First name:</label>
                    <span class="finput">
                    {{ newuserform.firstname }}
                    </span>
                    {{ newuserform.firstname.errors }}
                </div>
                
                <div class="frow">
                    <label for="id_lastname" class="flabel">Last name:</label>
                    <span class="finput">
                    {{ newuserform.lastname }}
                    </span>
                    {{ newuserform.lastname.errors }}
                </div>
                
                <div class="frow">
                    <label for="id_email" class="flabel">Email:</label>
                    <span class="finput">
                    {{ newuserform.email }}
                    </span>
                    {{ newuserform.email.errors }}
                </div>
                
                <div class="frow">
                    <label for="id_cert" class="flabel">Cert .pem:</label>
                    <span class="finput">
                    {{ newuserform.cert }} (not required)
                    </span>
                    {{ newuserform.cert.errors }}
                </div>
                
                <div class="frow">
                    <label for="id_key" class="flabel">Key .pem:</label>
                    <span class="finput">
                    {{ newuserform.key }} (not required)
                    </span>
                    {{ newuserform.key.errors }}
                </div>
                
                <div class="frow">
                    <label for="id_query_canonical" class="flabel">Canonical ID</label>
                    <span class="finput">
                    {{ newuserform.query_canonical }} (not required)
                    </span>
                    {{ newuserform.query_canonical.errors }}
                </div>

                <div class="frow">
                    <label for="id_query_id" class="flabel">Query ID</label>
                    <span class="finput">
                    {{ newuserform.query_id }} (not required)
                    </span>
                    {{ newuserform.query_id.errors }}
                </div>
                
                <div class="frow">
                    <label for="id_query_secret" class="flabel">Query Secret</label>
                    <span class="finput">
                    {{ newuserform.query_secret }} (not required)
                    </span>
                    {{ newuserform.query_secret.errors }}
                </div>
                
                <div class="frow">
                    <input type="hidden" name="op" value="newuser">
                    <input type="submit" value="Create User">
                </div>
            </form>
        </div>
    </div>
        
    <div class="section">
    
        <h1>Pending users</h1>
        
        <p>
            Pending users are those that have been issued accounts but have not logged in yet.
        </p>
        
        {% if pendingusers %}
        <table class="userlists">
            <thead>
                <tr>
                    <th>Username</th>
                    <th>Token expires at...</th>
                    <th>Token expires in...</th>
                </tr>
            </thead>
            <tbody>
            {% for puser in pendingusers %}
                <tr>
                    <td>{{ puser.user.username }}</td>
                    <td>{{ puser.date }}</td>
                    <td>{{ puser.expiresin }}</td>
                </tr>
            {% endfor %}
            <tbody>
        </table>
        {% else %}
        <ul><li>There are no pending users.</li></ul>
        {% endif %}
        
    </div>
        
    <div class="section">
        
        <h1>Current users</h1>
        <p>
            Currently, you can only edit the current users from the Django built-in
            <a href="/admin/">administration application</a>.
        </p>
        
        <p>
            Below is a list of the most recent initial logins, i.e., when the user clicked on the URL you mailed, the IP address used, etc.
        </p>
        
        {% if recentusers %}
        <table class="userlists">
            <thead>
                <tr>
                    <th>Username</th>
                    <th>Used token at...</th>
                    <th>Active user for...</th>
                    <th>Token use IP</th>
                    <th>Retrieved key at...</th>
                    <th>Key retrieval IP</th>
                </tr>
            </thead>
            <tbody>
            {% for ruser in recentusers %}
                <tr>
                    <td>{{ ruser.user.username }}</td>
                    
                    <td>{{ ruser.logindate }}</td>
                    
                    {% if ruser.activefor %}
                    <td>{{ ruser.activefor }}</td>
                    {% else %}
                    <td>n/a</td>
                    {% endif %}
                    
                    {% if ruser.regflag %}
                    <td><span class="keyflag">Did not finish registration</span></td>
                    {% else %}
                        {% if ruser.regip %}
                        <td>{{ ruser.regip }}</td>
                        {% else %}
                        <td>n/a</td>
                        {% endif %}
                    {% endif %}
                    
                    {% if ruser.keyflag %}
                    <td><span class="keyflag">Key present in DB</span></td>
                    <td>n/a</td>
                    {% else %}
                        {% if ruser.keydate %}
                        <td>{{ ruser.keydate }}</td>
                        <td>{{ ruser.keyip }}</td>
                        {% else %}
                        <td>n/a</td>
                        <td>n/a</td>
                        {% endif %}
                    
                    {% endif %}
                </tr>
            {% endfor %}
            <tbody>
        </table>
        {% else %}
        <ul><li>There are no recent users.</li></ul>
        {% endif %}
    </div>

{% endblock content %}

web/src/python/nimbusweb/portal/templates/nimbus/index.html
{% extends "base.html" %}
{% block content %}
    <p>
        {{ message }}
    </p>
    <p>
        If you already have an account, <a href="/nimbus/accounts/login?next=/nimbus/profile/">log in now</a>.
    </p>
    <p>
        If you do not have an account, {{ accountprompt }}
    </p>
{% endblock %}

web/src/python/nimbusweb/portal/templates/nimbus/login.html
{% extends "base.html" %}
{% block content %}
  {% if form.errors %}
    <p class="error">Sorry, that's not a valid username or password</p>
  {% endif %}
  
  <div class="loginuser">
      <form action="" method="post">
        
        <div class="frow">
            <label for="username" class="flabel">Username:</label>
            <span class="finput">
                <input type="text" name="username" value="" id="username">
            </span>
        </div>
        
        <div class="frow">
            <label for="password" class="flabel">Password:</label>
            <span class="finput">
                <input type="password" name="password" value="" id="password">
            </span>
        </div>
        
        <input type="hidden" name="next" value="{{ next|escape }}" />
        
        <div class="frow">
            <input type="submit" value="login" />
        </div>
      </form>
  </div>
{% endblock %}

web/src/python/nimbusweb/portal/templates/nimbus/logout.html
{% extends "base.html" %}
{% block content %}
   <p>
      Thanks for visiting.
   </p>
   <p>
      Popular links:
   </p>
   <ul>
       <li><a href="http://www.nimbusproject.org/docs/current/clouds/cloudquickstart.html">Cloud client quickstart</a></li>
       <li><a href="http://www.nimbusproject.org/docs/">Nimbus documentation</a></li>
   </ul>
   <p>
        Or, <a href="/nimbus/accounts/login?next=/nimbus/profile/">log in</a> again.
    </p>
{% endblock %}

web/src/python/nimbusweb/portal/templates/nimbus/password.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
    <h1>{% trans 'Password change' %}</h1>
    
    <p>{% trans "Please enter your old password and then enter your new password twice so we can verify you typed it in correctly." %}</p>
    
    <div class="changepw">
    <form action="" method="post">
    
        <div class="rrow">
            <label for="id_old_password" class="flabel">{% trans 'Old password:' %}</label> 
            <span class="finput">
            {{ form.old_password }}
            </span>
            {{ form.old_password.errors }}
        </div>
        
        <div class="rrow">
            <label for="id_new_password1" class="flabel">{% trans 'New password:' %}</label> 
            <span class="finput">
            {{ form.new_password1 }}
            </span>
            {{ form.new_password1.errors }}
        </div>
        
        <div class="rrow">
            <label for="id_new_password2" class="flabel">{% trans 'Confirm password:' %}</label> 
            <span class="finput">
            {{ form.new_password2 }}
            </span>
            {{ form.new_password2.errors }}
        </div>
    
        <p><input type="submit" value="{% trans 'Change my password' %}" /></p>
    </form>
    </div>

{% endblock %}

web/src/python/nimbusweb/portal/templates/nimbus/password_done.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
        
    <h1>{% trans 'Password change successful' %}</h1>
    
    <p>{% trans 'Your password was changed.' %}</p>
    
    <p>Back to <a href="/nimbus/profile">your profile</a></p>

{% endblock %}

web/src/python/nimbusweb/portal/templates/nimbus/profile.html
{% extends "base.html" %}

{% block title %}Your Profile{% endblock title %}

{% block content %}
    <p>
        {{ message }}
    </p>
    
    <h3>Your account</h3>
    <div class="profile">
        <div class="lrow">
            <span class="flabel">Username:</span>
            <span class="finput">{{ user.username }}</span>
        </div>
        {% if user.get_full_name %}
        <div class="lrow">
            <span class="flabel">Name:</span>
            <span class="finput">{{ user.get_full_name }}</span>
        </div>
        {% endif %}
        <div class="lrow">
            <span class="flabel">Email:</span>
            <span class="finput">{{ user.email }}</span>
        </div>
    </div>
    
    <br>
    
    <h3>Your credentials</h3>
    
    {% if cert_present or key_present or access_present or props_present %}
    <div id="credentials_container">
        <div class="credentials_box">
            <h4>X.509 certificate</h4>
            {% if key_present or cert_present %}
            <p>
                X.509 credentials are used with the cloud-client. They have
                two components: a public certificate and a private key.
            </p>

            <div class="lrow">
                <span class="flabel">Certificate</span>
                {% if cert_present %}
                <a href="usercert.pem">usercert.pem</a>
                {% else %}
                (not available)
                {% endif %}
            </div>
            <div class="lrow">
                <span class="flabel">Private key</span>
                {% if key_present %}
                <a href="userkey.pem">userkey.pem</a>
                {% else %}
                (not available)
                {% endif %}
            </div>

            <p><strong>
                For your protection, the private key can only be downloaded once.
            </strong></p>
            {% if not key_present %}
            <p>
                You do not have a private key available. Most likely, it has already
                been downloaded. If you did not download it or if you lost it, please
                contact the administrator immediately.
            </p>
            {% else %}

            <p>Instructions</p>
            <ol>
                <li>Download these files and place them into
                    <samp>~/.globus/</samp>, in your home directory. You may need
                    to create this directory.
                </li>
                <li>
                    Ensure that the private key is not world-readable:
                    <div><samp>chmod 600 ~/.globus/userkey.pem</samp></div>
                </li>
                <li>Follow the
                    <a href="http://www.nimbusproject.org/docs/current/clouds/cloudquickstart.html">
                        cloud client quickstart</a>.</li>
            </ol>
            {% endif %}


            {% else %}
            <p>You have no X.509 credentials on file.</p>
            {% endif %}
        </div>
        
        {% if props_present %}
        <div class="credentials_box">
            <h4>The cloud.properties file you should use</h4>
            <p>
                This cloud.properties file has all of the customizations
                necessary to get running on this cloud.  It includes your
                unique access credential for using the image repository, so
                protect the file accordingly.
            </p>
            <p>
                Copy this to the "conf/cloud.properties" file in your cloud
                client (or name it something different and use the --conf
                argument).
            </p>
            <p>
                <a href="cloud.properties">cloud.properties</a>
            </p>
        </div>
        {% endif %}

        {% if access_present %}
        <div class="credentials_box">
            <h4>Access token</h4>
            <p>
                Access tokens are used for the Nimbus EC2 Query API interface
                and for Cumulus/S3 repository.
                For information on using these tokens, check the
                <a href="http://www.nimbusproject.org/docs/current/elclients.html#boto">documentation</a>.
            </p>
            {% if props_present %}
            <p>
                <b>The cloud.properties file (just above) also contains these
                credentials.</b>
            </p>
            {% endif %}
            <div class="lrow" id="accesskey">
                <span class="flabel">Canonical</span>
                <span class="copybox">{{ canonical_id }}</span>
            </div>
            <div class="lrow" id="accesskey">
                <span class="flabel">User ID</span>
                <span class="copybox">{{ access_key }}</span>
            </div>
            <div class="lrow" id="accesssecret">
                <span class="flabel">Secret</span>
                <span class="copybox">{{ access_secret }}</span>
            </div>
        </div>
        {% endif %}

    </div>
    <br>
    {% else %}
    <p>None on file.</p>
    {% endif %}
    
    <h3>Other</h3>
        
    {% if user.is_superuser %}
    
    <p>
        You have access to the <a href="../admin/">administrator panel</a>
    </p>
    
    {% endif %} 
    
    <p>
        <a href="../accounts/password">Change your password</a>
    </p>
    
    <p>
        <a href="../accounts/logout">Log out</a>
    </p>
    
{% endblock %}

web/src/python/nimbusweb/portal/templates/nimbus/register.html
{% extends "base.html" %}
{% block content %}

    <h1>Registration</h1>

    <p>
        Your <b>username</b> is '{{ user.username }}'
    </p>
    
    <p>Choose a <b>password</b> with 12 characters or more:</p>
    
    <div class="register">
    <form action="" method="post">
    
        <div class="rrow">
            <span class="flabel">New password:</span>
            <span class="finput">
                <input type="password" name="new_password1">
            </span>
        </div>
            
        <div class="rrow">
            <span class="flabel">Confirm password:</span>
            <span class="finput">
                <input type="password" name="new_password2">
            </span>
        </div>
        
        <br>
        <br>
        
        <p>
            <b>Warning:</b> You will need to know your username and password
            after you submit this, in order to login.
        </p>
        
        <div class="rrow">
            <input type="submit" value="Choose password">
        </div>
    </form>
    </div>
    
    

{% endblock %}